// components/ContactHeader.vue
<template>
  <div class="bg-etio hidden lg:block">
    <div class="container mx-auto flex text-sm py-2">
      <div class="mr-6 text-white">
        <font-awesome-icon class="mr-1" icon="phone-alt" />
        <a href="tel:+33636924394">06.36.92.43.94</a>
      </div>
      <div class="mr-6 text-white">
        <font-awesome-icon class="mr-1" icon="map-marker-alt" /> 874 rue Sainte
        Catherine, 59495 LEFFRINCKOUCKE
      </div>
      <div class="mr-6 text-white">
        <font-awesome-icon class="mr-1" icon="at" />
        <a href="mailto:mnieuwjaer.etiopathe@outlook.fr"
          >mnieuwjaer.etiopathe@outlook.fr</a
        >
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({})
</script>

// src/app/contact-header.tsx
import { AtSymbolIcon, MapPinIcon, PhoneIcon } from "@heroicons/react/20/solid";
import Link from "next/link";

export const ContactHeader = () => {
  return (
    <section className="bg-primary hidden lg:block">
      <div className="container mx-auto flex text-sm py-2 text-white space-x-6">
        <div className="inline-flex items-center">
          <PhoneIcon className="h-5 w-5 mr-1" />
          <Link href="tel:+33777149098">07.77.14.90.98</Link>
        </div>
        <div className="inline-flex items-center">
          <MapPinIcon className="h-5 w-5 mr-1" /> 574 avenue du stade, 59240,
          Dunkerque
        </div>
        <div className="inline-flex items-center">
          <AtSymbolIcon className="h-5 w-5 mr-1" />
          <Link href="mailto:mnieuwjaer.etiopathe@gmail.com">
            mnieuwjaer.etiopathe@gmail.com
          </Link>
        </div>
      </div>
    </section>
  );
};
